# Generated by Django 3.2.6 on 2021-08-21 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('comments', models.TextField(default=None)),
                ('created_at', models.DateTimeField(verbose_name='Creation date')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('units', models.PositiveIntegerField(default=1)),
                ('comments', models.TextField(default=None)),
                ('shop_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_list.shoplist')),
            ],
        ),
    ]
