# Generated by Django 3.2.6 on 2021-08-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_list', '0002_alter_shoplist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoplist',
            name='comments',
            field=models.TextField(default=None, null=True),
        ),
    ]
