# Generated by Django 3.2.6 on 2021-08-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_list', '0003_alter_shoplist_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='comments',
            field=models.TextField(default=None, null=True),
        ),
    ]
